server.port=20790
spring.datasource.url=jdbc:postgresql://localhost:5432/gen_f972652468a5
spring.datasource.username=myuser
spring.datasource.password=mypassword
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.open-in-view=false
spring.flyway.enabled=true
springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.enabled=true
server.forward-headers-strategy=framework
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=never
admin.api-key=872bb6fa-3702-4d7e-bf4b-1d8e2f574509fc2d9c7e-4b0b-bdc4-3d6d8a1aa109
